repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -w -s --
        files: '\.go$'
        language: golang
        types: [ go ]
        description: "Runs `gofmt`, requires golang"
